### ISSUE TITLE
How to decode a Maybe Object?

### ISSUE THREAD

**Issue by Matthew-Mosior** [stefan-hoeck/idris2-json#16]
Hi,

Haskell's Aeson library allows to decode a constructor of a data type as a Maybe Object, but I am having trouble doing the same with this library.

Is this possible?

I see that there is an Object field of the JSON record, but am unsure of how to use it when trying to decode something.

For example,

```
record NFieldAttr where
 constructor MkNFieldAttr
 nfieldattrtype          : String
 nredcapfieldattrmapping : Maybe Object
```

returns the error:

```
Error: While processing constructor MkNFieldAttr. When unifying:
    Type -> Type -> Type
and:
    Type
Mismatch between: Type -> Type -> Type and Type.
```

**Comment by stefan-hoeck** [comment]
I'm not sure what you are trying to do. In Aeson, `Object` is a type alias for `KeyMap Value`. In this library, `Object` is an interface of type `Type -> Type -> Type`. Hence the error message you get.

I'm not sure yet, whether I should keep this layer of abstraction (abstracting over the `value` and `object` type). Anyway, abstracting over the value type means that encoding and decoding `Value` does some unnecessary extra work, so it is currently not yet implemented.

**Comment by Matthew-Mosior** [comment]
I suppose im trying to decode an `Object String String`, something like:

```
[{"name":"John", "birthplace":"Tampa"},{"name":"Matt","birthplace":"Chicago"}]
```

**Comment by stefan-hoeck** [comment]
What should be the Idris representation of the JSON string you posted? I don't know what `Object String String` is supposed to be. `Object` is an interface in module `JSON.Value`.

**Comment by Matthew-Mosior** [comment]
I think I what I probably want is to decode the example above as a `JObject` actually.

I just found this:

```
public export
data JSON : Type where
  JNull   : JSON
  JNumber : Double -> JSON
  JBool   : Bool   -> JSON
  JString : String -> JSON
  JArray  : List JSON -> JSON
  JObject : List (String, JSON) -> JSON
```

in https://github.com/stefan-hoeck/idris2-json/blob/cd3e660f549dbf69021364f02a8ad4ef749f97a9/src/JSON/Parser.idr

**Comment by stefan-hoeck** [comment]
Did you work through the tutorial that comes with this library? If you derive `ToJSON` and `FromJSON` as above, the decode will expect a JSON object with keys `"nfielddattrtype"` and `"nredcapfielddattrmapping"`. Both are not part of your JSON string.

**Comment by stefan-hoeck** [comment]
Perhaps it will be instructive to use the code you posted above, and encode a value of type `NFieldAttr` with function `JSON.ToJSON.encode`.

**Comment by Matthew-Mosior** [comment]
I did, but probably didnt understand it fully.

Here's a more complete representation of what is being parsed in my JSON example:

```
"nredcapfieldattrmapping": {
          "John": "john",
          "James": "james",
          "Matt": "matt",
          "Luke": "luke"
        }
```

The above is what is returning the `JErr ([Key "redcapcodebooknmapping", Key "nfieldattributemapping", Key "nredcapfieldattrmapping"], "parsing List failed, expected Array, but encountered Object")` error.

**Comment by stefan-hoeck** [comment]
OK, this took a considerable amount of time to figure out. Please, when asking for help, provide self-contained examples, including imports, with full input and output. Compared to your data types, there are fields missing in your JSON string (`nidentifierfield`), so I'm not sure what you want to do here.

Anyway, `List (String,String)` is encoded as a JSON Array not an Object, hence the error message you get. You need to define a custom data type for this, which will then be encoded as an object. The following worked for me:

```idris
import Derive.Prelude
import JSON.Derive
import JSON

%default total
%language ElabReflection

record KeyMap a where
  constructor KM
  pairs : List (String,a)

%runElab derive "KeyMap" [Show,Eq,Ord]

ToJSON a => ToJSON (KeyMap a) where
  toJSON (KM ps) = object $ (map . map) toJSON ps

FromJSON a => FromJSON (KeyMap a) where
  fromJSON = withObject "KeyMap" $ \obj =>
    KM <$> traverse (\(s,v) => (s,) <$> fromJSON v) (pairs obj)

record NFieldAttr where
  constructor MkNFieldAttr
  nfieldattrtype          : String
  nredcapfieldattrmapping : Maybe (KeyMap String)

%runElab derive "NFieldAttr" [Show,Eq,ToJSON,FromJSON]

record NFieldName where
  constructor MkNFieldName
  nprovisioningfieldname : String
  nredcapfieldname       : String

%runElab derive "NFieldName" [Show,Eq,ToJSON,FromJSON]

record REDCapNMapping where
  constructor MkREDCapNMapping
  nfieldnamemapping      : NFieldName
  nfieldattributemapping : NFieldAttr

%runElab derive "REDCapNMapping" [Show,Eq,ToJSON,FromJSON]


str : String
str = """
    {
          "nfieldnamemapping": {
            "nprovisioningfieldname": "a",
            "nredcapfieldname": "b"
          },
          "nfieldattributemapping": {
           "nfieldattrtype": "TYPEA",
           "nredcapfieldattrmapping": {
              "John": "john",
              "James": "james",
              "Matt": "matt",
              "Luke": "luke"
            }
      }
    }
  """
```

**Comment by Matthew-Mosior** [comment]
Thank you for all of you help, I apologize for not providing adequent information and background up-front.

This really helps, I see that I needed a custom data type to work through this.  Thanks again @stefan-hoeck!
