### ISSUE TITLE
Encoding record with 1 field doesn't work

### ISSUE THREAD

**Issue by raders** [stefan-hoeck/idris2-json#22]
```
record Config where
  constructor MkConfig
  test: String
```
Encoding MkConfig "test1" produces the string "test1" instead of the object {"test" : "test1"}

**Comment by stefan-hoeck** [comment]
This is expected behavior as it reflects the representation of such a record at runtime. However, I think this should be customizable via `JSON.Option.Options`. I'll look into it.

**Comment by Victor-Savu** [comment]
Hi @raders ! With the latest version of `idris2-json`, you can set `unwrapRecords` to `False` to get the most verbose expansion of the record, and set `sum` to `UntaggedValue` so that you only keep the "value" (which is the pair you want).

```idris
module Main

import Hedgehog
import JSON.Derive

%language ElabReflection

record Config where
  constructor MkConfig
  test: String

%runElab derive "Config" [Show,Eq,(customToJSON $ {sum:=UntaggedValue, unwrapRecords:=False} defaultOptions),(customFromJSON $ {sum:=UntaggedValue, unwrapRecords:=False} defaultOptions)]

main : IO ()
main = test . pure $ MkGroup "Maelstrom" [("#22", property $ encode (MkConfig "test1") ===  #"{"test":"test1"}"#)]
```

**Comment by raders** [comment]
Looks good. Thank you!

**Comment by stefan-hoeck** [comment]
I'm closing this as it seems this is now resolved.
